services:
  truth-01-bera:
    container_name: truth-01-bera
    build: .
    environment:
      - DATABASE_PATH=/app/data/prices.db
      - API_PORT=8001
      - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet.allora.network/
      - TOKEN=BERA
      - TOKEN_CG_ID=berachain
      - WORKER_TYPE=1
      - CGC_API_KEY=your_cgc_api_key
    ports:
      - "8001:8001"
    volumes:
      - ./truth-01-data/bera-data:/app/data

  updater-01-bera:
    container_name: updater-01-bera
    build:
      context: .
      dockerfile: Dockerfile_updater
    depends_on:
      - truth-01-bera
    environment:
      - DATA_PROVIDER_API_ADDRESS=http://truth-01-bera:8001

  truth-02-eth:
    container_name: truth-02-eth
    build: .
    environment:
      - DATABASE_PATH=/app/data/prices.db
      - API_PORT=8002
      - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet.allora.network/
      - TOKEN=ETH
      - TOKEN_CG_ID=ethereum
      - WORKER_TYPE=1
      - CGC_API_KEY=your_cgc_api_key
    ports:
      - "8002:8002"
    volumes:
      - ./truth-02-data/eth-data:/app/data

  updater-02-eth:
    container_name: updater-02-eth
    build:
      context: .
      dockerfile: Dockerfile_updater
    depends_on:
      - truth-02-eth
    environment:
      - DATA_PROVIDER_API_ADDRESS=http://truth-02-eth:8002

  reputer-01:
    container_name: reputer-01
    image: alloranetwork/allora-offchain-node:v0.9.1
    volumes:
      - ./worker-01-data:/data
    depends_on:
      - truth-01-bera
      - truth-02-eth
    env_file:
      - ./worker-01-data/env_file