services:
  updater:
    container_name: updater
    build:
      context: .
      dockerfile: Dockerfile_updater
    entrypoint: ["sh", "-c", "while true; do sleep 60; python -u /app/update_app.py; done"]
    environment:
      - TOKENS=BERA:bera
      - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet.allora.network/
      - DATABASE_PATH=/app/data/prices.db
      - CGC_API_KEY=CG-xxxxxxxxx
      - TIINGO_API_TOKEN=a99de96faaf30fc292a9c5b785974efa85708646
      - TIINGO_CACHE_DIR=/app/data/tiingo_cache
      - OKX_CACHE_DIR=/app/data/okx_cache
      - TIINGO_CACHE_TTL=3600
    volumes:
      - ./source-data:/app/data
    restart: unless-stopped

  source-01:
    container_name: source-01
    build: .
    environment:
      - DATABASE_PATH=/app/data/prices.db
      - API_PORT=8001
      - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet.allora.network/
      - TOKENS=BERA:bera
      - INTERVAL_STEPS=60
      - LOOK_BACK=60
      - PREDICTION_STEPS=60
      - PREDICTION_HORIZON=60
      - TIINGO_API_TOKEN=a99de9xxywtw62tdbj84fa85708646
      - TIINGO_CACHE_DIR=/app/data/tiingo_cache
      - OKX_CACHE_DIR=/app/data/okx_cache
      - TIINGO_CACHE_TTL=3600
      - MODELS_DIR=/app/models
    ports:
      - "8001:8001"
    command: >
      sh -c "python init_data.py && gunicorn --preload --bind 0.0.0.0:8001 --log-level info --error-logfile - --access-logfile -
      --worker-tmp-dir /dev/shm --graceful-timeout 120 --timeout 30 --keep-alive 5
      --worker-class gthread --workers 2 --threads 6 app:app"
    volumes:
      - ./source-data:/app/data
      - ./models:/app/models
    restart: unless-stopped

  allora-worker:
    container_name: allora-worker
    image: alloranetwork/allora-offchain-node:v0.10.0
    volumes:
      - ./worker-data:/data
    depends_on:
      - source-01
    env_file:
      - ./worker-data/env_file
    restart: unless-stopped
