services:
  updater:
    container_name: updater
    build:
      context: .
      dockerfile: Dockerfile_updater
    entrypoint: ["sh", "-c", "while true; do sleep 120; python -u /app/updater.py; done"]
    environment:
      - TOKENS=paxgusd
      - TIINGO_API_TOKEN=xxa99de96faaf30fc292a9c5b785974efa85708646
      - TIINGO_DATA_DIR=/app/data/tiingo_data
      - TIINGO_CACHE_TTL=150
    volumes:
      - ./source-data:/app/data
    restart: unless-stopped

  inference:
    container_name: inference
    build: .
    environment:
      - API_PORT=8000
      - TOKENS=paxgusd
      - LOOK_BACK=240
      - PREDICTION_HORIZON=1440
      - TIINGO_API_TOKEN=xxa99de96faaf30fc292a9c5b785974efa85708646
      - TIINGO_DATA_DIR=/app/data/tiingo_data
      - TIINGO_CACHE_TTL=150
      - MODELS_DIR=/app/models
    ports:
      - "8000:8000"
    command: >
      sh -c "python init_data.py && gunicorn --preload --bind 0.0.0.0:8000 --log-level info --error-logfile - --access-logfile -
      --worker-tmp-dir /dev/shm --graceful-timeout 120 --timeout 30 --keep-alive 5
      --worker-class gthread --workers 2 --threads 6 app:app"
    volumes:
      - ./source-data:/app/data
      - ./models:/app/models
    restart: unless-stopped

  allora-worker:
    container_name: allora-worker
    image: alloranetwork/allora-offchain-node:v0.12.0
    volumes:
      - ./worker-data:/data
    depends_on:
      - inference
    env_file:
      - ./worker-data/env_file
    restart: unless-stopped
